[build]
command = "npm run build"
publish = "./build/server/index.js"

[dev]
command = "npm run dev"
framework = "vite"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
